controller_list:
  - name: fake_arm_controller
    type: $(arg execution_type)
    joints:
      - shoulder_pan_joint
      - shoulder_pitch_joint
      - elbow_roll_joint
      - elbow_pitch_joint
      - wrist_roll_joint
      - wrist_pitch_joint
      - gripper_roll_joint
  - name: fake_gripper_controller
    type: $(arg execution_type)
    joints:
      - finger_joint1
      - finger_joint2
initial:  # Define initial robot poses.
#  - group: arm
#    pose: home

  []